GBAndroidL1HW
BayrTserenov/GBAndroidL1HW pull request #1
Opened 2021-05-31 09:30 UTC by BayrTserenov

Lesson1

2021-05-31 15:40 UTC, DwarfPorter commented
У вас отсутствуют gradle файлы, и сам плагин gradle. так проект собираться не будет, там бывает важная информация по проекту. Из-за этого студия не понимает что там внутри.

2021-05-31 15:42 UTC, DwarfPorter requested changes
Запустить не удалось. Пожалуйста закоммитьте сюда все файлы проекта

2021-05-31 15:42 UTC, DwarfPorter commented on app/src/main/java/com/example/gbandroidl1hw/SecondActivity.java
> +    Button button2;
private

2021-06-02 15:18 UTC, BayrTserenov commented on app/src/main/java/com/example/gbandroidl1hw/SecondActivity.java
> +    Button button2;
не очень понял.. должен быть private class?

2021-06-02 15:20 UTC, BayrTserenov commented on app/src/main/java/com/example/gbandroidl1hw/SecondActivity.java
> +    Button button2;
Добавил все что увидел в дереве проекта в гит, кроме игнор файлов. Запушил сюда

2021-06-02 15:20 UTC, merged